[programs.localnet]
counterapp = "HJqSGkR5hP5d51ywhYkuwGYF4Tj3aL8A6wNS9Q5dHrM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/anmol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
